# Generated by Django 5.2.16 on 2026-08-10 11:11

import apps.rotina.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0010_cliente_demonstracao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certidao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('federal', 'Federal (RFB/PGFN)'), ('estadual', 'Estadual'), ('municipal', 'Municipal'), ('fgts', 'FGTS (CRF)'), ('trabalhista', 'Trabalhista (CNDT)')], max_length=12)),
                ('situacao', models.CharField(choices=[('negativa', 'Negativa'), ('positiva_efeito', 'Positiva com efeito de negativa'), ('positiva', 'Positiva (há débito)')], max_length=20)),
                ('emitida_em', models.DateField()),
                ('valida_ate', models.DateField()),
                ('url_documento', models.URLField(blank=True, default='')),
                ('observacao', models.CharField(blank=True, default='', max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certidoes', to='clients.cliente')),
            ],
            options={
                'verbose_name': 'certidão',
                'verbose_name_plural': 'certidões',
                'ordering': ['tipo', '-valida_ate'],
                'indexes': [models.Index(fields=['cliente', 'valida_ate'], name='certidao_validade')],
            },
        ),
        migrations.CreateModel(
            name='Folha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', apps.rotina.models.Competencia(help_text='Mês de referência no formato AAAA-MM, ex.: 2026-07.', max_length=7)),
                ('funcionarios', models.PositiveIntegerField(default=0)),
                ('total_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_encargos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fechada_em', models.DateField(blank=True, null=True)),
                ('observacao', models.CharField(blank=True, default='', max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folhas', to='clients.cliente')),
            ],
            options={
                'verbose_name': 'folha',
                'verbose_name_plural': 'folhas',
                'ordering': ['-competencia'],
                'constraints': [models.UniqueConstraint(fields=('cliente', 'competencia'), name='folha_unica_por_competencia')],
            },
        ),
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('das', 'DAS — Simples Nacional'), ('darf', 'DARF'), ('gps', 'GPS — INSS'), ('fgts', 'FGTS'), ('iss', 'ISS municipal')], max_length=10)),
                ('competencia', apps.rotina.models.Competencia(help_text='Mês de referência no formato AAAA-MM, ex.: 2026-07.', max_length=7)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vencimento', models.DateField()),
                ('situacao', models.CharField(choices=[('aberta', 'Em aberto'), ('paga', 'Paga'), ('cancelada', 'Cancelada')], default='aberta', max_length=12)),
                ('url_documento', models.URLField(blank=True, default='', help_text='Link do PDF da guia, se houver.')),
                ('codigo_barras', models.CharField(blank=True, default='', help_text='Linha digitável, para o cliente pagar sem abrir o arquivo.', max_length=60)),
                ('observacao', models.CharField(blank=True, default='', max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guias', to='clients.cliente')),
            ],
            options={
                'verbose_name': 'guia',
                'verbose_name_plural': 'guias',
                'ordering': ['-competencia', 'tipo'],
                'indexes': [models.Index(fields=['cliente', 'situacao', 'vencimento'], name='guia_fila')],
                'constraints': [models.UniqueConstraint(fields=('cliente', 'tipo', 'competencia'), name='guia_unica_por_competencia')],
            },
        ),
        migrations.CreateModel(
            name='Obrigacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('dctfweb', 'DCTFWeb'), ('efd', 'EFD-Contribuições'), ('esocial', 'eSocial'), ('sped', 'SPED Fiscal'), ('defis', 'DEFIS')], max_length=12)),
                ('competencia', apps.rotina.models.Competencia(help_text='Mês de referência no formato AAAA-MM, ex.: 2026-07.', max_length=7)),
                ('prazo', models.DateField()),
                ('situacao', models.CharField(choices=[('pendente', 'Pendente'), ('enviada', 'Enviada'), ('dispensada', 'Dispensada')], default='pendente', max_length=12)),
                ('pendente_com_o_cliente', models.BooleanField(default=False)),
                ('observacao', models.CharField(blank=True, default='', max_length=200)),
                ('enviada_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obrigacoes', to='clients.cliente')),
            ],
            options={
                'verbose_name': 'obrigação',
                'verbose_name_plural': 'obrigações',
                'ordering': ['-competencia', 'tipo'],
                'indexes': [models.Index(fields=['cliente', 'situacao', 'prazo'], name='obrigacao_fila')],
                'constraints': [models.UniqueConstraint(fields=('cliente', 'tipo', 'competencia'), name='obrigacao_unica_por_competencia')],
            },
        ),
    ]
