# Generated by Django 5.2.16 on 2026-08-09 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0009_nivel_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('chamado', 'Chamado'), ('atendimento', 'Pedido de atendimento')], default='chamado', max_length=20)),
                ('assunto', models.CharField(help_text='Resumo curto, montado pelo núcleo — nunca inventado pelo modelo.', max_length=120)),
                ('descricao', models.TextField(blank=True, default='', help_text='O que o cliente escreveu, nas palavras dele.')),
                ('preferencia_data', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('aberta', 'Aberta'), ('em_andamento', 'Em andamento'), ('resolvida', 'Resolvida')], default='aberta', max_length=20)),
                ('canal', models.CharField(default='whatsapp', max_length=20)),
                ('protocolo', models.CharField(help_text='O que o cliente cita quando cobra. Gerado no núcleo, estável.', max_length=24, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('resolvido_em', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='clients.cliente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes', to='clients.usuario')),
            ],
            options={
                'verbose_name': 'solicitação',
                'verbose_name_plural': 'solicitações',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['cliente', 'estado'], name='solicitacao_cliente_estado')],
            },
        ),
    ]
