# Generated by Django 5.2.16 on 2026-07-25 14:58

import apps.credentials.crypto
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoEvolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='padrão', help_text="Só identificação — ex.: 'instância de testes'.", max_length=60)),
                ('base_url', models.URLField(help_text='URL da instância, ex.: https://evolution.seudominio.com')),
                ('instancia', models.CharField(help_text='Nome da instância cadastrada na Evolution.', max_length=100)),
                ('api_key_cifrada', apps.credentials.crypto.CampoTextoCifrado(blank=True, help_text='Cifrada em repouso — nunca reexibida depois de salva.', null=True)),
                ('ativo', models.BooleanField(default=False, help_text='Só a configuração ativa mais recente é usada pelo canal.')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'configuração Evolution (teste local)',
                'verbose_name_plural': 'configurações Evolution (teste local)',
            },
        ),
    ]
