# Generated by Django 5.2.16 on 2026-07-26 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel_evolution', '0001_initial'),
        ('painel', '0002_multitenancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoevolution',
            name='escritorio',
            field=models.ForeignKey(blank=True, help_text='Escritório dono desta instância. Em branco = configuração global de bootstrap (só faz sentido em instalação de um tenant só).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes_evolution', to='painel.escritorio'),
        ),
    ]
