# Generated by Django 5.2.16 on 2026-07-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExemploIntencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frase', models.CharField(help_text='Como o cliente falaria. ⚠ Não cole a mensagem real de um cliente: troque nome, CNPJ e valores por exemplos genéricos.', max_length=300, unique=True)),
                ('intencao', models.CharField(choices=[('emitir_nota', 'Emitir nota fiscal'), ('consultar_nota', 'Consultar notas emitidas'), ('cancelar_nota', 'Cancelar nota emitida'), ('consultar_estoque', 'Consultar estoque'), ('consultar_pedido', 'Consultar pedidos/vendas'), ('consultar_contas_receber', 'Contas a receber'), ('consultar_contas_pagar', 'Contas a pagar'), ('consultar_fluxo_caixa', 'Fluxo de caixa'), ('desconhecida', 'Nenhuma das anteriores')], max_length=40)),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para tirar do prompt sem perder o registro.')),
                ('observacao', models.CharField(blank=True, default='', help_text='Por que este exemplo existe — ex.: “cliente chamou nota de recibo”.', max_length=300)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'exemplo de intenção',
                'verbose_name_plural': 'exemplos de intenção',
                'ordering': ['intencao', 'frase'],
            },
        ),
    ]
