# Generated by Django 5.2.16 on 2026-07-25 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agente_nf', '0001_initial'),
        ('clients', '0003_cliente_email_contato_perfil_valor_2fa_acima_de'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codigo2FA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_hash', models.CharField(max_length=64)),
                ('tentativas', models.PositiveSmallIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateTimeField()),
                ('usado_em', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_2fa', to='clients.cliente')),
                ('intencao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_2fa', to='agente_nf.intencao')),
            ],
            options={
                'verbose_name': 'código 2FA',
                'verbose_name_plural': 'códigos 2FA',
            },
        ),
        migrations.CreateModel(
            name='SessaoWhatsapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wa_id', models.CharField(blank=True, default='', help_text='Número validado na última ativação — comparado ao telefone atual do cliente a cada mensagem.', max_length=32)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('ativa', 'Ativa'), ('expirada', 'Expirada'), ('bloqueada', 'Bloqueada')], default='pendente', max_length=20)),
                ('validado_em', models.DateTimeField(blank=True, null=True)),
                ('expira_em', models.DateTimeField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sessao_whatsapp', to='clients.cliente')),
            ],
            options={
                'verbose_name': 'sessão WhatsApp',
                'verbose_name_plural': 'sessões WhatsApp',
            },
        ),
        migrations.CreateModel(
            name='TokenMagicLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wa_id', models.CharField(max_length=32)),
                ('jti', models.CharField(max_length=64, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usado_em', models.DateTimeField(blank=True, null=True)),
                ('expira_em', models.DateTimeField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magic_links', to='clients.cliente')),
            ],
            options={
                'verbose_name': 'token de Magic Link',
                'verbose_name_plural': 'tokens de Magic Link',
            },
        ),
    ]
