# Generated by Django 5.2.16 on 2026-08-09 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_nivel_usuario'),
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaEmFoco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, help_text='Empresa escolhida. Vazio = menu enviado, resposta pendente.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foco_de_usuarios', to='clients.cliente')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='foco', to='clients.usuario')),
            ],
            options={
                'verbose_name': 'empresa em foco',
                'verbose_name_plural': 'empresas em foco',
            },
        ),
    ]
