# Generated by Django 5.2.16 on 2026-07-26 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0006_cliente_codigo_municipio_ibge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerieDps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(default='1', max_length=5)),
                ('ultimo_numero', models.PositiveBigIntegerField(default=0)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_dps', to='clients.cliente')),
            ],
            options={
                'verbose_name': 'série da DPS',
                'verbose_name_plural': 'séries da DPS',
                'constraints': [models.UniqueConstraint(fields=('cliente', 'serie'), name='serie_dps_unica_por_cliente')],
            },
        ),
    ]
