# Generated by Django 5.2.16 on 2026-07-08 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('evento', models.CharField(max_length=64)),
                ('dados', models.JSONField(default=dict)),
                ('hash_anterior', models.CharField(blank=True, default='', max_length=64)),
                ('hash_atual', models.CharField(max_length=64)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auditorias', to='clients.cliente')),
            ],
            options={
                'verbose_name': 'auditoria',
                'verbose_name_plural': 'auditorias',
                'ordering': ['id'],
            },
        ),
    ]
