# Generated by Django 5.2.16 on 2026-07-27 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('clients', '0007_campos_fiscais_dps'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChaveConteudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_cifrada', models.BinaryField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('destruida_em', models.DateTimeField(blank=True, help_text='Preenchido na eliminação a pedido do titular.', null=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chave_conteudo', to='clients.cliente')),
            ],
            options={
                'verbose_name': 'chave de conteúdo (LGPD)',
                'verbose_name_plural': 'chaves de conteúdo (LGPD)',
            },
        ),
    ]
