# Generated by Django 5.2.16 on 2026-07-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escritorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex.: "Rotina Contábil".', max_length=120)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('cor_primaria', models.CharField(default='#1a1a2e', help_text='Hex, ex.: #000066. Usada no cabeçalho do painel.', max_length=7)),
                ('cor_acento', models.CharField(default='#5B67C9', help_text='Hex — links e destaques do painel.', max_length=7)),
                ('ativo', models.BooleanField(default=False, help_text='Só o escritório ativo mais recente aparece no painel.')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'escritório (tenant)',
                'verbose_name_plural': 'escritórios (tenants)',
            },
        ),
    ]
