# Generated by Django 5.2.16 on 2026-07-08 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('telefone_whatsapp', models.CharField(help_text='Número no formato internacional, ex.: 5511999998888', max_length=20, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.CharField(default='lumen', max_length=40)),
                ('ferramentas_habilitadas', models.JSONField(default=list, help_text='Adaptadores/ferramentas ativos, ex.: ["erp_mock", "nfse_mock"]')),
                ('tier_maximo', models.PositiveSmallIntegerField(default=1)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='clients.cliente')),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfis',
            },
        ),
    ]
