# Generated by Django 5.2.16 on 2026-07-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cnae_padrao',
            field=models.CharField(blank=True, default='', help_text='CNAE do serviço prestado, cadastrado pelo contador — nunca inferido pelo LLM (guard determinístico da emissão fiscal).', max_length=10),
        ),
    ]
