# Generated by Django 5.2.16 on 2026-07-25 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_cliente_cnae_padrao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email_contato',
            field=models.EmailField(blank=True, default='', help_text='E-mail cadastrado na Receita/ERP — canal do Magic Link e do código 2FA. Nunca reaproveitar o WhatsApp como canal desses segredos (2º fator de canal).', max_length=254),
        ),
        migrations.AddField(
            model_name='perfil',
            name='valor_2fa_acima_de',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Emissões acima deste valor exigem código de 2FA por e-mail (apps/security). Vazio = 2FA desligado para este cliente.', max_digits=10, null=True),
        ),
    ]
