# Generated by Django 5.2.16 on 2026-07-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_cliente_escritorio_tenants'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='codigo_municipio_ibge',
            field=models.CharField(blank=True, default='', help_text='Código IBGE do município (7 dígitos) — `cLocEmi`/`cLocPrestacao` da DPS.', max_length=7),
        ),
        migrations.AddField(
            model_name='cliente',
            name='codigo_tributacao_nacional',
            field=models.CharField(blank=True, default='', help_text='`cTribNac` — 6 dígitos da lista nacional de serviços (LC 116). É ESTE que vai na nota, não o CNAE. Cadastrado pelo contador, nunca inferido pelo LLM.', max_length=6),
        ),
        migrations.AddField(
            model_name='cliente',
            name='inscricao_municipal',
            field=models.CharField(blank=True, default='', help_text='Inscrição municipal do prestador (`prest.IM`). Opcional em alguns municípios.', max_length=15),
        ),
        migrations.AddField(
            model_name='cliente',
            name='regime_tributario',
            field=models.PositiveSmallIntegerField(blank=True, help_text='`prest.regTrib` — regime de tributação do prestador (tabela da NT vigente).', null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='serie_dps',
            field=models.CharField(blank=True, default='1', help_text='Série da DPS (`serie`). Numeração sequencial é por prestador+série.', max_length=5),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cnae_padrao',
            field=models.CharField(blank=True, default='', help_text='CNAE do serviço prestado, cadastrado pelo contador — nunca inferido pelo LLM (guard determinístico da emissão fiscal). ⚠ NÃO é o que vai na DPS: a NFS-e Nacional usa `codigo_tributacao_nacional` (cTribNac). CNAE é classificação de atividade econômica, serve pro cadastro.', max_length=10),
        ),
    ]
