# Generated by Django 5.2.16 on 2026-07-26 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_cliente_codigo_municipio_ibge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='regime_tributario',
        ),
        migrations.AddField(
            model_name='cliente',
            name='aliquota_iss',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="`trib.tribMun.pAliq` em % (ex.: 2.00). Vazio = não declarada — cabível para MEI/Simples, onde o recolhimento não é por alíquota de ISS na nota. Nunca preencher com valor 'padrão' chutado.", max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='iss_retencao',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Não retido'), (2, 'Retido pelo tomador'), (3, 'Retido pelo intermediário')], default=1, help_text='`trib.tribMun.tpRetISSQN` — obrigatório na DPS.'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='iss_tributacao',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Operação tributável'), (2, 'Exportação de serviço'), (3, 'Não incidência / imunidade'), (4, 'Exigibilidade suspensa')], default=1, help_text='`trib.tribMun.tribISSQN` — obrigatório na DPS.'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='opcao_simples_nacional',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Não optante'), (2, 'Optante — MEI'), (3, 'Optante — ME/EPP')], default=1, help_text='`regTrib.opSimpNac` — enquadramento no Simples Nacional.'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='regime_especial_tributacao',
            field=models.PositiveSmallIntegerField(default=0, help_text='`regTrib.regEspTrib` — 0 = nenhum; 1 a 6 conforme tabela da NT vigente.'),
        ),
    ]
