# Generated by Django 5.2.16 on 2026-07-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_campos_fiscais_dps'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='data_inicio_atividade',
            field=models.DateField(blank=True, help_text='Data de abertura na Receita — preenchida pela consulta pública. Usada só para o teto proporcional do MEI no ano de abertura (quem abre em julho tem direito a meio teto, não ao teto cheio). Vazia = o radar de teto assume o ano inteiro e diz isso na tela.', null=True),
        ),
    ]
