# Generated by Django 5.2.16 on 2026-08-10 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_nivel_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='demonstracao',
            field=models.BooleanField(default=False, help_text='Empresa fictícia, criada para demonstração. Aparece marcada na carteira.'),
        ),
    ]
