# Generated by Django 5.2.16 on 2026-07-08 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('oauth', 'OAuth2'), ('procuracao', 'Procuração eletrônica'), ('certificado', 'Certificado digital (via middleware)'), ('token', 'Token de API')], max_length=20)),
                ('referencia_cofre', models.CharField(help_text='ARN/chave do segredo no cofre — NUNCA o segredo em si.', max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credenciais', to='clients.cliente')),
            ],
            options={
                'verbose_name': 'credencial',
                'verbose_name_plural': 'credenciais',
            },
        ),
    ]
