# Generated by Django 5.2.16 on 2026-07-11 23:30

import apps.credentials.crypto
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AplicativoIntegracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('conta_azul', 'Conta Azul'), ('bling', 'Bling'), ('nfse_nacional', 'NFS-e Nacional (Emissor Nacional/ADN)')], max_length=30, unique=True)),
                ('ambiente', models.CharField(default='homologacao', help_text='"homologacao" ou "producao".', max_length=20)),
                ('base_url', models.URLField(help_text='⚠ preencher com a URL vigente da API (muda entre homologação/produção).')),
                ('token_url', models.URLField(blank=True, default='', help_text='Endpoint OAuth2 de token, se aplicável.')),
                ('client_id', models.CharField(blank=True, default='', max_length=255)),
                ('client_secret_cifrado', apps.credentials.crypto.CampoTextoCifrado(blank=True, null=True)),
                ('ativo', models.BooleanField(default=False, help_text='Só usado pelo resolver de adapters se ativo.')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'aplicativo de integração',
                'verbose_name_plural': 'aplicativos de integração',
            },
        ),
        migrations.AddField(
            model_name='credencial',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='credencial',
            name='expira_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='credencial',
            name='integracao',
            field=models.CharField(blank=True, default='', help_text='Ex.: "conta_azul", "bling", "nfse_nacional" — casa com AplicativoIntegracao.nome.', max_length=30),
        ),
        migrations.AddField(
            model_name='credencial',
            name='valor_cifrado',
            field=apps.credentials.crypto.CampoTextoCifrado(blank=True, help_text='Piloto: access/refresh token ou identificador da procuração, cifrado com Fernet.', null=True),
        ),
        migrations.AlterField(
            model_name='credencial',
            name='referencia_cofre',
            field=models.CharField(blank=True, default='', help_text='Produção: ARN/chave no Secrets Manager. Deixe em branco no piloto.', max_length=255),
        ),
    ]
