# Generated by Django 5.2.16 on 2026-07-25 10:00

import apps.credentials.crypto
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_aplicativointegracao_credencial_atualizado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credencial',
            name='certificado_cnpj',
            field=models.CharField(blank=True, default='', help_text='CNPJ extraído do certificado — conferir contra Cliente.cnpj antes de ativar.', max_length=14),
        ),
        migrations.AddField(
            model_name='credencial',
            name='certificado_validade',
            field=models.DateField(blank=True, help_text='Data de expiração do certificado.', null=True),
        ),
        migrations.AddField(
            model_name='credencial',
            name='pfx_arquivo_cifrado',
            field=models.BinaryField(blank=True, help_text='Upload do .pfx, cifrado em repouso (Fernet) — nunca em texto puro. Preencher só via o campo de upload do admin, nunca editar direto.', null=True),
        ),
        migrations.AddField(
            model_name='credencial',
            name='pfx_senha_cifrada',
            field=apps.credentials.crypto.CampoTextoCifrado(blank=True, help_text='Senha do .pfx, cifrada separadamente do arquivo.', null=True),
        ),
        migrations.AddField(
            model_name='credencial',
            name='psc_identificador',
            field=models.CharField(blank=True, default='', help_text='Identificador da assinatura remota no PSC (ex.: e-mail/CPF vinculado ao certificado).', max_length=100),
        ),
        migrations.AddField(
            model_name='credencial',
            name='psc_provedor',
            field=models.CharField(blank=True, default='', help_text='Ex.: "birdid", "vidaas", "safeid" — só para tipo Certificado em nuvem (PSC).', max_length=40),
        ),
        migrations.AlterField(
            model_name='credencial',
            name='tipo',
            field=models.CharField(choices=[('oauth', 'OAuth2'), ('procuracao', 'Procuração eletrônica (gov.br) — consentimento/fallback, não autentica API'), ('certificado_psc', 'Certificado digital em nuvem (PSC)'), ('certificado_pfx', 'Certificado digital — arquivo .pfx'), ('token', 'Token de API')], max_length=20),
        ),
    ]
