# Generated by Django 5.2.16 on 2026-07-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membroescritorio',
            name='responsavel',
            field=models.BooleanField(default=False, help_text='Pode convidar e remover colegas DESTE escritório. Não é um papel de permissão (isso é o Grupo do Django) — é só a capacidade de gerir a própria equipe.'),
        ),
    ]
