# Generated by Django 5.2.16 on 2026-08-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_rls_nivel_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='escritorio',
            name='limite_gasto_mensal_brl',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Teto mensal de gasto com IA deste escritório, em reais. Acima de 80% o assistente passa a usar o modelo barato na extração de campos; acima de 100% ele responde só pelo determinístico. Em nenhum dos casos o atendimento para. Vazio = sem teto.', max_digits=10, null=True),
        ),
    ]
