# Generated by Django 5.2.16 on 2026-07-08 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_idempotencia', models.CharField(max_length=100, unique=True)),
                ('tipo_acao', models.CharField(default='emitir_nfse', max_length=40)),
                ('payload', models.JSONField(default=dict)),
                ('estado', models.CharField(choices=[('RECEBIDO', 'Recebido'), ('VALIDANDO', 'Validando'), ('AGUARDANDO_APROVACAO', 'Aguardando aprovação'), ('EMITINDO', 'Emitindo'), ('CONCLUIDO', 'Concluído'), ('REJEITADO', 'Rejeitado'), ('CANCELADO', 'Cancelado')], default='RECEBIDO', max_length=24)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intencoes_fiscais', to='clients.cliente')),
            ],
            options={
                'verbose_name': 'intenção fiscal',
                'verbose_name_plural': 'intenções fiscais',
            },
        ),
    ]
