# Generated by Django 5.2.16 on 2026-07-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agente_nf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intencao',
            name='danfse_url',
            field=models.URLField(blank=True, default='', help_text='Link do DANFSE — preenchido na emissão bem-sucedida.'),
        ),
        migrations.AddField(
            model_name='intencao',
            name='protocolo',
            field=models.CharField(blank=True, default='', help_text='Preenchido na emissão bem-sucedida (CONCLUIDO).', max_length=100),
        ),
    ]
