# Generated by Django 5.2.16 on 2026-07-26 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agente_nf', '0002_intencao_danfse_url_intencao_protocolo'),
    ]

    operations = [
        migrations.AddField(
            model_name='intencao',
            name='cancelada_em',
            field=models.DateTimeField(blank=True, help_text='Preenchido na NOTA quando o cancelamento é aceito.', null=True),
        ),
        migrations.AddField(
            model_name='intencao',
            name='intencao_original',
            field=models.ForeignKey(blank=True, help_text="Só para tipo_acao='cancelar_nfse': a nota que se quer cancelar.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_cancelamento', to='agente_nf.intencao'),
        ),
        migrations.AddField(
            model_name='intencao',
            name='protocolo_cancelamento',
            field=models.CharField(blank=True, default='', help_text='Protocolo do evento de cancelamento.', max_length=100),
        ),
    ]
