# Generated by Django 5.2.16 on 2026-07-26 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agente_nf', '0003_cancelamento_de_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='intencao',
            name='chave_nfse',
            field=models.CharField(blank=True, default='', help_text='Chave de acesso da NFS-e (50 dígitos), devolvida pela Sefin na autorização. NÃO é o protocolo: protocolo identifica o processamento, a chave identifica o documento — e é a chave que o evento de cancelamento exige.', max_length=50),
        ),
    ]
