# Generated by Django 5.2.16 on 2026-08-10 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agente_nf', '0005_painel_analitico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(choices=[('cliente_whatsapp', 'Cliente, pelo WhatsApp'), ('contador_painel', 'Contador, no Grimório'), ('equipe_admin', 'Equipe, pelo admin')], max_length=20)),
                ('wa_id', models.CharField(blank=True, default='', max_length=20)),
                ('usuario', models.CharField(blank=True, default='', max_length=150)),
                ('referencia', models.CharField(blank=True, default='', help_text='`message_id` do WhatsApp, ou vazio quando a origem é o painel.', max_length=100)),
                ('exigiu_2fa', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('intencao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmacoes', to='agente_nf.intencao')),
            ],
            options={
                'verbose_name': 'confirmação',
                'verbose_name_plural': 'confirmações',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['intencao', 'criado_em'], name='confirmacao_intencao')],
            },
        ),
    ]
