# Generated by Django 5.2.16 on 2026-08-10 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0010_cliente_demonstracao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('desconhecido', 'A classificar'), ('nota_entrada', 'Nota de entrada'), ('nota_servico', 'Nota de serviço'), ('boleto', 'Boleto'), ('extrato', 'Extrato bancário'), ('contrato', 'Contrato'), ('outro', 'Outro')], default='desconhecido', max_length=20)),
                ('situacao', models.CharField(choices=[('aguardando_revisao', 'Aguardando revisão'), ('classificado', 'Classificado'), ('recusado', 'Recusado')], default='aguardando_revisao', max_length=20)),
                ('origem', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('painel', 'Enviado no painel')], default='whatsapp', max_length=12)),
                ('bucket', models.CharField(max_length=80)),
                ('chave', models.CharField(max_length=300)),
                ('nome_arquivo', models.CharField(max_length=200)),
                ('tipo_mime', models.CharField(blank=True, default='', max_length=100)),
                ('tamanho', models.PositiveIntegerField(default=0)),
                ('hash_sha256', models.CharField(db_index=True, help_text='Identifica o arquivo sem baixá-lo — é como reenvio do mesmo documento é reconhecido.', max_length=64)),
                ('dados_extraidos', models.JSONField(blank=True, default=dict, help_text='Chave de acesso, valor, CNPJ emitente, vencimento. Vazio enquanto não há OCR.')),
                ('confianca', models.PositiveSmallIntegerField(default=0, help_text='0 a 100. Começa em zero e assim permanece sem OCR — e zero nunca vira lançamento automático, que é o gate do sprint.')),
                ('protocolo', models.CharField(help_text='O que o cliente cita ao cobrar. Gerado no núcleo, estável.', max_length=24, unique=True)),
                ('observacao', models.CharField(blank=True, default='', max_length=200)),
                ('revisado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='clients.cliente')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_revisados', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='clients.usuario')),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['cliente', 'situacao'], name='documento_cliente_situacao')],
            },
        ),
    ]
