# Generated by Django 5.2.16 on 2026-08-09 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0009_nivel_usuario'),
        ('tenants', '0005_escritorio_limite_gasto_mensal_brl'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumoLLM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(choices=[('roteador', 'Classificação de intenção'), ('extracao', 'Extração de campos')], max_length=20)),
                ('modelo', models.CharField(help_text='Identificador exato do modelo chamado — é a chave da tabela de preços.', max_length=80)),
                ('tokens_entrada', models.PositiveIntegerField(default=0)),
                ('tokens_saida', models.PositiveIntegerField(default=0)),
                ('tokens_cache_leitura', models.PositiveIntegerField(default=0, help_text='Tokens de entrada servidos do cache do provedor, cobrados pela metade. Medi-los separado é o que permite responder, com número, se o system prompt por tenant compensa (DEC-08 item 4).')),
                ('requisicoes', models.PositiveIntegerField(default=1, help_text='Chamadas HTTP reais — retry de validação do Pydantic AI conta.')),
                ('tool_calls', models.PositiveIntegerField(default=0)),
                ('latencia_ms', models.PositiveIntegerField(default=0, help_text='Tempo da chamada ao modelo, do envio à resposta validada.')),
                ('custo_brl', models.DecimalField(decimal_places=6, default=0, help_text='Seis casas porque uma mensagem custa frações de centavo — arredondar para dois zeraria toda linha e a soma do mês daria zero.', max_digits=12)),
                ('erro', models.CharField(blank=True, default='', max_length=200)),
                ('momento', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumo_llm', to='clients.cliente')),
                ('escritorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumo_llm', to='tenants.escritorio')),
            ],
            options={
                'verbose_name': 'consumo de LLM',
                'verbose_name_plural': 'consumo de LLM',
                'indexes': [models.Index(fields=['escritorio', 'momento'], name='consumo_escritorio_momento'), models.Index(fields=['cliente', 'momento'], name='consumo_cliente_momento')],
            },
        ),
    ]
